### ISSUE TITLE
Information about skim object column types should be removed

### ISSUE THREAD

**Issue by GegznaV** [ropensci/skimr#384] opened 2019-02-01 17:19 UTC
If skim summary spans more than one row, aditional column type information of skim object (i.e., not original dataset) should be removed. Illustration:

![image](https://user-images.githubusercontent.com/12725868/52138464-e2c2be80-2655-11e9-8202-e498494d240c.png)

**Comment by elinw** [comment] 2019-02-02 14:11
Oh that's interesting .. which branch are you using?

**Comment by GegznaV** [comment] 2019-02-02 17:13
```r
devtools::install_github("ropenscilabs/skimr", ref = "v2")
```

**Comment by elinw** [comment] 2019-02-02 19:33
I guess that options for that may be separate than those for the full display.

**Comment by elinw** [comment] 2019-02-27 01:24
@GegznaV would you take a look at the PR for this?

**Comment by GegznaV** [comment] 2019-02-27 15:31
I installed `remotes::install_github("ropenscilabs/skimr", ref = "v2-print")` and ran `skimr::skim(iris)`.
Can't see any difference:
![image](https://user-images.githubusercontent.com/12725868/53501758-6cc74100-3ab5-11e9-9d2c-71a46bb767bc.png)

**Comment by elinw** [comment] 2019-03-12 04:49
Weird that it's wrapping .

**Comment by michaelquinn32** [comment] 2019-03-16 17:29
I'm having trouble reproducing. Sorry about that. But I'll keep an eye out for anything weird after we get everything into v2.

**Comment by elinw** [comment] 2019-03-24 21:58
Okay I merged the branch but there is still @GegznaV 's issue that we can't reproduce.  Can you try updating to the v2 branch and trying again?   I'm not getting that wrapping at all.

**Comment by GegznaV** [comment] 2019-03-25 00:38
Now works as expected.

**Comment by GegznaV** [comment] 2019-03-25 00:41
Could you also add additional space before each `-- Variable type:` row? As this feature was present in v1. (Should I open a new issue for this?)

**Comment by elinw** [comment] 2019-03-25 00:43
Please open a new issue but I experimented with this and it is hard to get it to work across console and knitted results (because of html and rmarkdown treatment of spaces).

**Closed** 2019-03-25 01:40 UTC
