### ISSUE TITLE
development version of `tibble` breaks `skimr`

### ISSUE THREAD

**Issue by IndrajeetPatil** [ropensci/skimr#552] opened 2019-12-10 21:44 UTC
``` r
library(skimr)
skimr::skim(iris)
#> Error: Tibble columns must have consistent lengths, only values of length one are recycled:
#> * Length 0: Column `skim_variable`
#> * Length 2: Columns `skim_type`, `skimmers`

rlang::last_error()
#> Error: Can't show last error because no error was recorded yet
```

```r
> rlang::last_error()
<error/tibble_error_inconsistent_cols>
Tibble columns must have consistent lengths, only values of length one are recycled:
* Length 0: Column `skim_variable`
* Length 2: Columns `skim_type`, `skimmers`

Backtrace:
 1. skimr::skim(iris)
 2. tibble::tibble(...)
 3. tibble:::tibble_quos(xs[!is_null], .rows, .name_repair)
 4. tibble:::lst_to_tibble(output, .rows, .name_repair, lengths = lengths)
 5. tibble:::recycle_columns(x, .rows, lengths)
Run `rlang::last_trace()` to see the full context.
```

```r
> rlang::last_trace()
<error/tibble_error_inconsistent_cols>
Tibble columns must have consistent lengths, only values of length one are recycled:
* Length 0: Column `skim_variable`
* Length 2: Columns `skim_type`, `skimmers`
Backtrace:
    x
 1. \-skimr::skim(iris)
 2.   \-tibble::tibble(...)
 3.     \-tibble:::tibble_quos(xs[!is_null], .rows, .name_repair)
 4.       \-tibble:::lst_to_tibble(output, .rows, .name_repair, lengths = lengths)
 5.         \-tibble:::recycle_columns(x, .rows, lengths)
```

<sup>Created on 2019-12-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.6.1 (2019-07-05)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       Europe/Berlin               
#>  date     2019-12-10                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version      date       lib source                           
#>  assertthat    0.2.1        2019-03-21 [1] CRAN (R 3.6.0)                   
#>  backports     1.1.5        2019-10-02 [1] CRAN (R 3.6.1)                   
#>  base64enc     0.1-3        2015-07-28 [1] CRAN (R 3.5.0)                   
#>  callr         3.4.0        2019-12-09 [1] CRAN (R 3.6.1)                   
#>  cli           2.0.0        2019-12-09 [1] CRAN (R 3.6.1)                   
#>  crayon        1.3.4        2017-09-16 [1] CRAN (R 3.5.1)                   
#>  desc          1.2.0        2019-11-11 [1] Github (r-lib/desc@61205f6)      
#>  devtools      2.2.1        2019-09-24 [1] CRAN (R 3.6.1)                   
#>  digest        0.6.23       2019-11-23 [1] CRAN (R 3.6.1)                   
#>  dplyr         0.8.3.9000   2019-10-10 [1] Github (tidyverse/dplyr@dcfc1d1) 
#>  ellipsis      0.3.0        2019-09-20 [1] CRAN (R 3.6.1)                   
#>  evaluate      0.14         2019-05-28 [1] CRAN (R 3.6.0)                   
#>  fansi         0.4.0        2018-11-05 [1] Github (brodieG/fansi@ab11e9c)   
#>  fs            1.3.1        2019-05-06 [1] CRAN (R 3.6.0)                   
#>  glue          1.3.1        2019-03-12 [1] CRAN (R 3.6.0)                   
#>  highr         0.8          2019-03-20 [1] CRAN (R 3.6.0)                   
#>  htmltools     0.4.0        2019-10-04 [1] CRAN (R 3.6.1)                   
#>  jsonlite      1.6          2018-12-07 [1] CRAN (R 3.6.0)                   
#>  knitr         1.26         2019-11-12 [1] CRAN (R 3.6.1)                   
#>  magrittr      1.5          2014-11-22 [1] CRAN (R 3.5.1)                   
#>  memoise       1.1.0        2017-04-21 [1] CRAN (R 3.6.0)                   
#>  pillar        1.4.2.9001   2019-12-10 [1] Github (r-lib/pillar@82370d7)    
#>  pkgbuild      1.0.6        2019-10-09 [1] CRAN (R 3.6.1)                   
#>  pkgconfig     2.0.3        2019-09-22 [1] CRAN (R 3.6.1)                   
#>  pkgload       1.0.2        2018-10-29 [1] CRAN (R 3.6.0)                   
#>  prettyunits   1.0.2        2015-07-13 [1] CRAN (R 3.5.1)                   
#>  processx      3.4.1        2019-07-18 [1] CRAN (R 3.6.1)                   
#>  ps            1.3.0        2018-12-21 [1] CRAN (R 3.6.0)                   
#>  purrr         0.3.3        2019-10-18 [1] CRAN (R 3.6.1)                   
#>  R6            2.4.1        2019-11-12 [1] CRAN (R 3.6.1)                   
#>  Rcpp          1.0.3        2019-11-08 [1] CRAN (R 3.6.1)                   
#>  remotes       2.1.0        2019-06-24 [1] CRAN (R 3.6.0)                   
#>  repr          1.0.1        2019-05-14 [1] CRAN (R 3.6.0)                   
#>  rlang         0.4.2        2019-11-23 [1] CRAN (R 3.6.1)                   
#>  rmarkdown     1.18         2019-11-27 [1] CRAN (R 3.6.1)                   
#>  rprojroot     1.3-2        2018-01-03 [1] CRAN (R 3.5.1)                   
#>  sessioninfo   1.1.1        2018-11-05 [1] CRAN (R 3.6.0)                   
#>  skimr       * 2.0.2        2019-11-26 [1] CRAN (R 3.6.1)                   
#>  stringi       1.4.3        2019-03-12 [1] CRAN (R 3.6.0)                   
#>  stringr       1.4.0        2019-02-10 [1] CRAN (R 3.6.0)                   
#>  testthat      2.3.1        2019-12-01 [1] CRAN (R 3.6.1)                   
#>  tibble        2.99.99.9010 2019-12-10 [1] Github (tidyverse/tibble@f4365f7)
#>  tidyselect    0.2.5        2018-10-11 [1] CRAN (R 3.5.1)                   
#>  usethis       1.5.1.9000   2019-11-28 [1] Github (r-lib/usethis@c7314cf)   
#>  vctrs         0.2.0.9007   2019-12-10 [1] Github (r-lib/vctrs@3bca8ae)     
#>  withr         2.1.2        2018-03-15 [1] CRAN (R 3.5.1)                   
#>  xfun          0.11         2019-11-12 [1] CRAN (R 3.6.1)                   
#>  yaml          2.2.0        2018-07-25 [1] CRAN (R 3.5.1)                   
#> 
#> [1] C:/Users/inp099/Documents/R/win-library/3.6
#> [2] C:/Program Files/R/R-3.6.1/library
```

</details>

**Comment by michaelquinn32** [comment] 2019-12-12 21:23
Thanks for reporting. I'll take a look.

**Comment by elinw** [comment] 2019-12-22 06:55
We got that message before for something ... maybe a rlang change?

**Comment by elinw** [comment] 2019-12-22 07:33
Okay this is what we are getting on appveyor, maybe it explains why we could never reproduce it.

```
https://ci.appveyor.com/project/michaelquinn32/skimr/builds/29064353/job/t856oj78ydxl99ku
 ### Name: focus
> ### Title: Only show a subset of summary statistics after skimming
> ### Aliases: focus
>
> ### ** Examples
>
> # Compare
> iris %>%
+   skim() %>%
+   dplyr::select(n_missing)
Error: Tibble columns must have consistent lengths, only values of length one are recycled:
* Length 0: Column `skim_variable`
* Length 2: Columns `skim_type`, `skimmers`
<error/tibble_error_inconsistent_cols>
Tibble columns must have consistent lengths, only values of length one are recycled:
* Length 0: Column `skim_variable`
* Length 2: Columns `skim_type`, `skimmers`
Backtrace:
     x
  1. \-iris %>% skim() %>% dplyr::select(n_missing)
  2.   +-base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
  3.   \-base::eval(quote(`_fseq`(`_lhs`)), env, env)
  4.     \-base::eval(quote(`_fseq`(`_lhs`)), env, env)
  5.       \-`_fseq`(`_lhs`)
  6.         \-magrittr::freduce(value, `_function_list`)
  7.           \-function_list[[i]](value)
  8.             \-skimr::skim(.)
  9.               \-tibble::tibble(...)
 10.                 \-tibble:::tibble_quos(xs[!is_null], .rows, .name_repair)
 11.                   \-tibble:::lst_to_tibble(output, .rows, .name_repair, lengths = lengths
Execution halted
* checking for unstated dependencies in 'tests' ... OK
* checking tests ...
```

**Comment by elinw** [comment] 2019-12-22 12:28
I'm going to put this link here as well https://github.com/tidyverse/tibble/blob/4131c9ea9ea208dd28ddc8b43933e975774865fc/revdep/problems.md#skimr

This looks like it was run on skimer 1, however.

**Comment by elinw** [comment] 2019-12-30 07:33
So it looks as though there has been a major refactoring of tibble::tibble(). 
Currently with the github version data frames with a single type of variable will not error but will produce a wrong result, such as for mtcars 
```
# A tibble: 0 x 2
# … with 2 variables: skim_type <chr>, skimmed <???>
```
and the same for lynx.

But with two or more types we get the error.

**Comment by elinw** [comment] 2020-01-01 18:29
Okay please try this.  I did have to skip two tests for now.
https://github.com/ropensci/skimr/pull/560

**Comment by elinw** [comment] 2020-01-11 11:49
This is now fixed in the development branch.

**Closed by elinw** 2020-01-11 11:49 UTC
