### ISSUE TITLE
Histograms and line graphs not rendering on Windows

### ISSUE THREAD

**Issue by elinw** [ropensci/skimr#525] opened 2019-11-10 22:56 UTC
There is a known issue in which the in-line histograms and line graphs do not render correctly in windows. This is due to an issue that is deep within the handling of special characters (UTF-8) in Windows and in data frames on the R side of things.  

**In the console** this can sometimes be addressed by making some specific changes to locale as outlined in the documentation.

**In rmarkdown documents**  there may be some instances where you can generate better results, but in general on Windows you will have to simply not try to display the graphs.  There are multiple ways to do this described in the documentation.

**Comment by mik3y64** [comment] 2019-12-07 08:38
Is there a timeline of when this issue will be fixed? Without main features of histograms and line graphs, Windows users can't use it.

**Comment by michaelquinn32** [comment] 2019-12-09 18:32
Hi!

The issue is beyond the scope of `skimr` and is tied to R's lack of full support for unicode text.

There is a lot of documentation on and tools for how to work around the issue on windows, including

* the function fix_windows_histograms(): https://docs.ropensci.org/skimr/reference/fix_windows_histograms.html
* the function skim_without_charts(): https://docs.ropensci.org/skimr/reference/skim.html
* the fonts vignette: docs.ropensci.org/skimr/articles/Using_fonts.html

Try some of these and see if they help.

Best wishes,
Michael

**Closed by michaelquinn32** 2019-12-09 18:32 UTC
Labels: Information for users, wontfix

**Comment by bwiernik** [comment] 2020-09-08 01:26
See here for a discussion of this longstanding issue with UTF-8 in R for Windows and how it might possibly be resolved: https://developer.r-project.org/Blog/public/2020/07/30/windows/utf-8-build-of-r-and-cran-packages/index.html

**Comment by elinw** [comment] 2025-07-28 18:47
We upped the R minimum ro 4.1 because of the pipe. The question is should we require 4.2 or still keeping it that we recommend 4.2 for Windows users?

**Comment by michaelquinn32** [comment] 2025-08-31 18:56
R is at 4.5. I don't see a problem updating to 4.2
